### ISSUE TITLE
Categories do not return valid JSON.

### ISSUE THREAD

**Issue by imanrousta** [keikaavousi/fake-store-api#10]
When I try to access products of a category, for example ` /products/category/jewelery`, I get invalid-json response.

**Comment by keikaavousi** [comment]
> When I try to access products of a category, for example ` /products/category/jewelery`, I get invalid-json response.

I have checked this endpoint just now, and it didn't have any problem. https://fakestoreapi.com/products/category/jewelery

Can you send me the exact error you have got?

**Comment by imanrousta** [comment]
Thanks for the response. I rechecked the endpoint and now it works fine.
