### ISSUE TITLE
connect ECONNREFUSED

### ISSUE THREAD

**Issue by rrawann** [keikaavousi/fake-store-api#106]
How can solve this issue FetchError: request to https://fakestoreapi.com/products , reason: connect ECONNREFUSED 188.114.96.6:443

**Comment by khanguslee** [comment]
Do you have a code snippet on how you got that error? I am able to fetch data via that endpoint.

**Comment by rrawann** [comment]
This is a code snippt @khanguslee   , it was working and fetching data without any issues 


![api](https://github.com/keikaavousi/fake-store-api/assets/101040863/ac0b46e3-d74d-4c0e-8d62-7e3dda775eca)

**Comment by khanguslee** [comment]
Your code looks good to me. Can you check if it works now? Sometimes the API is down as you can see from past closed issues.

Note that the API is a free service, so I wouldn't be shocked if people were unintentionally causing the server to crash.

**Comment by rrawann** [comment]
Yes it is work now after I run npm run build for the project, Thank you very much @khanguslee
