### ISSUE TITLE
Real shop API compatibility

### ISSUE THREAD

**Issue by krnlde** [keikaavousi/fake-store-api#12]
Nice library. A better use case would be if you had (or had the possibility to add) api compatibility to real e commerce store apis, like strapi or commerce-layer. Is there any hidden compatibility that is not mentioned in the docs or do you plan to add adapters?
The usecase should be self explanatory.

Cheers :)

**Comment by keikaavousi** [comment]
> Nice library. A better use case would be if you had (or had the possibility to add) api compatibility to real e commerce store apis, like strapi or commerce-layer. Is there any hidden compatibility that is not mentioned in the docs or do you plan to add adapters?
> 
> The usecase should be self explanatory.
> 
> 
> 
> Cheers :)

Thank you for your comment. Yes it is in my plan to use the real world e-commerce API in the future.
