### ISSUE TITLE
API doesn’t working

### ISSUE THREAD

**Issue by ibrahimaberete** [keikaavousi/fake-store-api#120]
Hello, i have probleme with the API, I have code status 502
<img width="1314" alt="image" src="https://github.com/keikaavousi/fake-store-api/assets/47101718/cac6e83d-2113-4641-855e-8e529a299270">
 can you fix the issue please ?

**Comment by ayhanmetin** [comment]
Yes, I have the same issue. 
<img width="849" alt="apidown" src="https://github.com/keikaavousi/fake-store-api/assets/108268012/50a106a9-66a3-448c-9af7-775072a6c67d">

**Comment by mortadha1144** [comment]
Me too
![Screenshot 2023-11-28 151802](https://github.com/keikaavousi/fake-store-api/assets/105784062/1565977a-6087-4dcc-a3eb-71a420dcbc63)

**Comment by narkreeta** [comment]
same for me too , any idea when it will available ?

**Comment by Antonio-Banderas** [comment]
If anyone needs it in a pinch, here's the products.json. 

[products.json](https://github.com/keikaavousi/fake-store-api/files/13488785/products.json)

**Comment by keikaavousi** [comment]
It'll be fixed within a minute
Sorry for the inconvenience guys

**Comment by ibrahimaberete** [comment]
thank you !
