### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by fadilhim** [keikaavousi/fake-store-api#13]
Hi, thanks for the project it helps me to build my project. but apparently there's something wrong when I try to hit the API, here's im attach the image.
can you help me explain what's wrong?
![Screenshot 2021-04-19 194457](https://user-images.githubusercontent.com/47060060/115239530-0eec8c00-a149-11eb-9886-6a6db30ec2cb.png)

**Comment by keikaavousi** [comment]
> Hi, thanks for the project it helps me to build my project. but apparently there's something wrong when I try to hit the API, here's im attach the image.
> 
> can you help me explain what's wrong?
> 
> ![Screenshot 2021-04-19 194457](https://user-images.githubusercontent.com/47060060/115239530-0eec8c00-a149-11eb-9886-6a6db30ec2cb.png)
> 
> 
> 
> 
> 
> 

Hi, the problem had been resolved now. You can enjoy it :)
