### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by daminvo** [keikaavousi/fake-store-api#132]
Hello 

I get this error "Connection timed out Error code 522" when I try to open the website.
as well as Cors errors when sending requests to any endpoint.

can you please check ?

![Screenshot 2024-05-14 at 13 18 37](https://github.com/keikaavousi/fake-store-api/assets/39976713/691344d9-dfdc-4fce-bb8d-fc5ae562fd54)

**Comment by TrinhCDanh** [comment]
Me too! when I called the api today I also got error code 522

**Comment by keikaavousi** [comment]
There was a problem on infrastructure, it's working fine now!
