### ISSUE TITLE
About the store mock data

### ISSUE THREAD

**Issue by songhn233** [keikaavousi/fake-store-api#15]
Hi, i am a developer whose target language is not English and I also want to generate store mock data.

So i am curious about how the data is generated for this repository and i hope to get an answer.

**Comment by keikaavousi** [comment]
> Hi, i am a developer whose target language is not English and I also want to generate store mock data.
> 
> So i am curious about how the data is generated for this repository and i hope to get an answer.

Hi,
The data are fetching from the database. I have plan to add multiple language support for this repository. so if you can contribute to your desired language please email me at keikaavousi@gmail.com
