### ISSUE TITLE
Problem with CORS 

### ISSUE THREAD

**Issue by pswitalski** [keikaavousi/fake-store-api#21]
I'm trying to login user and always have this error: 

> Access to fetch at 'https://fakestoreapi.com/auth/login' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by saksham7** [comment]
I am also having a problem with login...
The token i get in response is invalid when checked on jwt.io and i cannot decode and get user details from it.
Can anybody please guide?

**Comment by keikaavousi** [comment]
@pswitalski you should send a header with your request ('content-type' : application/json,'accept':'application/json')
also, the token is just a sample one for testing, not a real complete token.
