### ISSUE TITLE
FakeStore API and website both are down and giving 502 error

### ISSUE THREAD

**Issue by codephrases** [keikaavousi/fake-store-api#27]
@keikaavousi @Bardiesel @jacob-ebey @mkeikaavousi Guys your API and website both are down and giving 502 error https://fakestoreapi.com
https://fakestoreapi.com/products
Please fix it.
![Screenshot (1)](https://user-images.githubusercontent.com/24953919/129280754-b419fe0d-3afe-4293-9e31-46f95244fb08.png)

**Comment by stanstancee** [comment]
Please attend to this. My demo website depends on your data

**Comment by deepakgudi-pixel** [comment]
Getting the same error as well please fix it.

**Comment by keikaavousi** [comment]
Problem solved

**Comment by deepakgudi-pixel** [comment]
Thank you!!

**Comment by codephrases** [comment]
Thank you
