### ISSUE TITLE
[Typo] Second Item has a string on the count instead of an Int

### ISSUE THREAD

**Issue by Djallil14** [keikaavousi/fake-store-api#31]
Hello,
There is a String instead of an Int in the second Item count of the products list.
<img width="1359" alt="Screen Shot 2021-09-03 at 12 18 47 AM" src="https://user-images.githubusercontent.com/82174673/131949927-4c00607d-e403-4d1d-b78d-ae15e60e168f.png">

**Comment by keikaavousi** [comment]
Thanks for your report. It's now an integer
