### ISSUE TITLE
FakeStoreApi down?

### ISSUE THREAD

**Issue by joelkarh** [keikaavousi/fake-store-api#32]
hi Guys

I was trying to fetch some data using axios for a list of products but i keep getting the same ssues  'Unexpected token < in JSON at position 0' , is is possible to fix this ? 

kind regards ,

Joël Karhamaba
<img width="1087" alt="Schermafbeelding 2021-09-12 om 21 23 47" src="https://user-images.githubusercontent.com/62657228/133000145-9ec5ce10-f669-4b0c-b89d-b0f4f1305ae9.png">
<img width="1087" alt="Schermafbeelding 2021-09-12 om 21 21 43" src="https://user-images.githubusercontent.com/62657228/133000151-62999cb0-e821-45d7-81f7-4b0e4ff7ee1f.png">

**Comment by gr1d99** [comment]
Yeah I think it is down, I have been trying to create users but it is not responding.

**Comment by keikaavousi** [comment]
It's working, please send me the request and response you got.

**Comment by gr1d99** [comment]
I think it is the user's endpoint only, I have tried the products endpoint and it works.

<img width="1008" alt="Screenshot 2021-09-16 at 16 10 35" src="https://user-images.githubusercontent.com/15877982/133618091-500ee638-8d12-46fa-86be-1b4244b6120c.png">

**Comment by keikaavousi** [comment]
Ok, I'll resolve this issue and let you know.

**Comment by gr1d99** [comment]
Alright

**Comment by Hani-AS** [comment]
Down again? it takes forever to get a response.

**Comment by keikaavousi** [comment]
It's working. Maybe because of request traffic you got time out. Send me
your curl or request you send.

**Comment by gr1d99** [comment]
It keeps timing out, 
![Uploading Screenshot 2021-09-23 at 06.45.36.png…]()

**Comment by gr1d99** [comment]
<img width="1014" alt="Screenshot 2021-09-23 at 06 45 36" src="https://user-images.githubusercontent.com/15877982/134451927-85747b6d-0622-461b-9d1b-7b660a374c61.png">

**Comment by keikaavousi** [comment]
Thanks, I'll check it out.

**Comment by prasadltp** [comment]
Hi, 

When i tried to add a new user with the details shared in the example(https://fakestoreapi.com/users). I am getting the below error. I have attached a screenshot. Could you plz check and let me know?
<img width="1765" alt="screenshot" src="https://user-images.githubusercontent.com/33217432/134485088-22319ed0-75d5-424b-b5f3-06601f691164.png">

**Comment by gr1d99** [comment]
@prasadltp the data you are sending is not a valid JSON, you need to wrap the keys and values in double quotes **(")** , eg

```json
{
  "email": "johndoe@mail.com"
}
```

Refer to [this](https://github.com/keikaavousi/fake-store-api/issues/32#issuecomment-925486383)

**Comment by prasadltp** [comment]
Hi,

Send the JSON data in double quotes as suggested. Now i am getting a timeout error. Please find the attached screenshot and suggest.
<img width="1763" alt="Screenshot 2021-09-23 at 4 57 28 PM" src="https://user-images.githubusercontent.com/33217432/134499564-53c94173-df4f-49b1-94e4-8821dbaa31ae.png">

**Comment by croshim** [comment]
Hey, API for "Add a new user" is still not working. Hope you'll fix that soon!

**Comment by keikaavousi** [comment]
Hi there!
"Add a new user" API problem has been solved. feel free to use it. @croshim @gr1d99 @prasadltp @joelkarh

**Comment by gr1d99** [comment]
Thank you
