### ISSUE TITLE
Status Code for Login Error

### ISSUE THREAD

**Issue by alinaserinet** [keikaavousi/fake-store-api#33]
Hello.
I think when username and password are incorrect is better that return the status code 401.
but API always returns status code 200!

**Comment by levi-ren** [comment]
Hi. Any updates for this?

**Comment by keikaavousi** [comment]
@alinaserinet @levi-ren 
Hi, Thanks for your feedback. I have changed this part and login API now returns "401" for unauthorize usernames with this message: "username or password is incorrect"
