### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by Mynameisfrostwalker** [keikaavousi/fake-store-api#34]
Hi I was trying to fetch data from the fake-store API but I received this error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fakestoreapi.com/products?limit=5. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing.

This is my code:

`    
fetch("https://fakestoreapi.com/products?limit=5", {
      mode: "cors",
      "content-type": "application/json",
      accept: "application/json",
    })
      .then((res) => res.json())
      .then((json) => console.log(json));
`

**Comment by keikaavousi** [comment]
It's working now. let me know if it doesn't work.

**Comment by feelthefreedom** [comment]
> It's working now. let me know if it doesn't work.

CORS related error reappeared ```auth/login```
