### ISSUE TITLE
Works very slowly

### ISSUE THREAD

**Issue by slava-lu** [keikaavousi/fake-store-api#36]
Dose someone monitor the performace of this API?

**Comment by keikaavousi** [comment]
Yes, nowadays, because of requests raised, it slows down. I should update
the server to perform smoothly.

**Comment by slava-lu** [comment]
Thanks for the reply. Do you plan to do it? It really not just slow.  I have timeout 6 sec and it timeouts. So I get the error and can't just use it.

**Comment by slava-lu** [comment]
So you closed this issue because you don't want to fix it?

**Comment by keikaavousi** [comment]
Do you still have this problem?
I upgrade the main server so I think it resolved the problem. If your
problem is not resolved yet, I will change the infrastructure ASAP.
Sorry again if you have trouble with this.

**Comment by keikaavousi** [comment]
Could you please send me the request you had timeout on?

**Comment by slava-lu** [comment]
Thanks for the quick response. After you replied, it started working fast again. The requests I had trouble with were:
`products?limit=15`
`/carts/1`
