### ISSUE TITLE
User registration issue

### ISSUE THREAD

**Issue by mirtizakh** [keikaavousi/fake-store-api#37]
Unable to register a user by calling this API https://fakestoreapi.com/users , method post .
I am not able to get the updated id , always giving me id = 11 in response .

![APi fail](https://user-images.githubusercontent.com/25367409/142634694-86c4b8e2-92a7-46a2-844a-dc9f0c985e77.png)

**Comment by keikaavousi** [comment]
At this time, FakeStoreApi registration does not really register a user
account. It just return the user you post. The next version of FakeStoreApi
will have this real feature.
