### ISSUE TITLE
Product image backgrounds

### ISSUE THREAD

**Issue by Jriera** [keikaavousi/fake-store-api#39]
It would be desirable to get the product images without the white background as it is obtrusive when trying to use the images on any background different from white.

**Comment by keikaavousi** [comment]
It will be changed in the next version of FakeStoreApi!

**Comment by clebemachado** [comment]
![image](https://user-images.githubusercontent.com/66011013/154704111-38818790-2f09-4a5f-8c84-a4ac720a1e8e.png)

I could help by removing the funds haha.

:)
