### ISSUE TITLE
editProduct return type of id field

### ISSUE THREAD

**Issue by frenzyfunky** [keikaavousi/fake-store-api#40]
Hello,

The type of id field in the response data of PUT https://fakestoreapi.com/products/7 request is string. In the docs at https://fakestoreapi.com/docs it shows id field as an integer.

I consume this api from .NET application and types can be a problem while deserializing. Would it be better if it is checked in the api side? with something like isNaN function? or should i handle this in my application?

**Comment by keikaavousi** [comment]
this problem is resolved now.
