### ISSUE TITLE
payment request

### ISSUE THREAD

**Issue by ANaSHaker** [keikaavousi/fake-store-api#41]
Hello, how are you
Thank you for developing this project. I am currently building a training application for me, and your project is really useful to me
I'm just wondering if you can soon build a payment api like a request that asks for data for example and I send it so that it is an integrated store project and everyone who uses your project I think needs something like that, so it will be useful for everyone

**Comment by keikaavousi** [comment]
Hi,
Thank you for your feedback, this feature will be in the next version of fakestoreApi.

**Comment by keikaavousi** [comment]
> Hello, how are you Thank you for developing this project. I am currently building a training application for me, and your project is really useful to me I'm just wondering if you can soon build a payment api like a request that asks for data for example and I send it so that it is an integrated store project and everyone who uses your project I think needs something like that, so it will be useful for everyone

Hi,
Thank you for your feedback, this feature will be in the next version of fakestoreApi.
