### ISSUE TITLE
The site https://fakestoreapi.com is down

### ISSUE THREAD

**Issue by mathiasgodwin** [keikaavousi/fake-store-api#43]
Pls the API isn't working and I really need for the project I'm working on right now. I hope you fix this. Thanks in advance

**Comment by keikaavousi** [comment]
Hi @mathiasgodwin, It's working fine. could you please check it again or send me the request you are sending?

**Comment by mathiasgodwin** [comment]
> Hi @mathiasgodwin, It's working fine. could you please check it again or send me the request you are sending?

Sorry, I think problem was from my ISP.

**Comment by keikaavousi** [comment]
Are you still have this issue?

**Comment by anthonykimani** [comment]
Hello, the API  is down . It has a 502 error.
