### ISSUE TITLE
Fake store api isn't working

### ISSUE THREAD

**Issue by MubashirWaheed** [keikaavousi/fake-store-api#55]
Pretty much what the title says and also the website is down.

**Comment by keikaavousi** [comment]
The infrastructure has lots of problem today and I will change the server
tonight.

**Comment by MubashirWaheed** [comment]
Thanks

**Comment by SOM3-1** [comment]
@keikaavousi  same issue

**Comment by keikaavousi** [comment]
It's working now.

**Comment by SOM3-1** [comment]
Thank you

**Comment by Ibrahim-yanal** [comment]
same issue
