### ISSUE TITLE
https://fakestoreapi.com is down

### ISSUE THREAD

**Issue by Basil-Code** [keikaavousi/fake-store-api#58]

**Comment by anthonykimani** [comment]
Yes, I'm also encountering this issue.

**Comment by JuliansRecent** [comment]
I'm also experiencing the API being down.

**Comment by keikaavousi** [comment]
@Basil-Code @anthonykimani  @JuliansRecent  It's working now

**Comment by anthonykimani** [comment]
Thank you very much, sir. @keikaavousi
