### ISSUE TITLE
Fake Store API is down

### ISSUE THREAD

**Issue by omerfarukatas** [keikaavousi/fake-store-api#59]
Hi, https://fakestoreapi.com/ is giving a 502 error. I am a student at a frontend bootcamp, we need to demo our e-commerce projects in 12 hours but the api is not working. Could you please take a look at it? Thanks in advance!

**Comment by JuliansRecent** [comment]
> 

LOL, I used the same API and just presented with the API down, good luck!

**Comment by Amaterasu-hash** [comment]
I'm facing the same issues

**Comment by keikaavousi** [comment]
@omerfarukatas @JuliansRecent @Amaterasu-hash  It's working now.
