### ISSUE TITLE
Fake-store-API Taking too much time to respond. 

### ISSUE THREAD

**Issue by yeasin2002** [keikaavousi/fake-store-api#60]
Fake-store-API Taking too much time to respond. 
Fetching 20 product data but taking 17.94 seconds.
it  Is too much time I think.   

![Screenshot (67)](https://user-images.githubusercontent.com/87494463/179367348-146751de-791d-498e-b891-1fd009446036.png)

**Comment by keikaavousi** [comment]
Hi, thank you for your feedback. It is because of the high volume of
requests. I have made some changes to improve its performance right now. so
please check it again and let me know if any problem exists.

**Comment by yeasin2002** [comment]
Now It's Working.
I tested also it today, it took only 660ms at that time. 
Thanks
