### ISSUE TITLE
Login Token should contain User Id

### ISSUE THREAD

**Issue by ducnguyen-peter** [keikaavousi/fake-store-api#61]
Like the title, some get request requires an user ID (user data, cart), but when I decode the token I only see the username and iat, which aren't helpful because get user data and user cart by name aren't supported.

Here is what the payload looks like when I decoded it online. It should return an user ID instead of just username.

<img width="1679" alt="Screen Shot 2022-08-01 at 10 43 30" src="https://user-images.githubusercontent.com/59559728/182068095-37ca884a-bb61-4519-899a-25e521a29938.png">

**Comment by keikaavousi** [comment]
Thanks for your suggestion. it will be fixed in the next version ASAP.
