### ISSUE TITLE
Updating user always returns 500 status code

### ISSUE THREAD

**Issue by Dawid-Witkowski** [keikaavousi/fake-store-api#63]
Currently writing an app in kotlin and encountered a problem while writing the "update user" part, no matter what data I send along the request (as a body) it always returns 500 status code, tried using postman and even requests (python library) to test it, no result.
Example:
`
link = "https://fakestoreapi.com/users/7"

data = {
    'email': 'John@gmail.com',
    'username': 'johnd',
    'password': 'password',
    'name': {'firstname': 'John', 'lastname': "Doe"},
    'address': {'city': 'kilcoole', 'street': '7835 new road', 'number': '3',
                'geolocation': {'lat': '-37.3159', 'long': '81.1496'}},
    'phone': '1-570-236-7033'
}

request = requests.put(link, data=data)
print(request.status_code)
`

**Comment by federicoviceconti** [comment]
Hi @Dawwit0001! I think the problem is the `lastname` parameter and change the data method parameter to json, like the example below:

```
import requests

x = requests.put('https://fakestoreapi.com/users/7',
                 json={
                     'email': 'John@gmail.com',
                     'username': 'johnd',
                     'password': 'password',
                     'name': {
                         'firstname': 'John',
                         'lastname': 'Doe'
                     },
                     'address': {
                         'city': 'kilcoole',
                         'street': '7835 new road',
                         'number': '3',
                         'geolocation': {
                             'lat': '-37.3159',
                             'long': '81.1496'
                         }
                     },
                     'phone': '1-570-236-7033'
                 })

print(x)
```

For Postman, import this cURL:
```
curl --location --request PUT 'https://fakestoreapi.com/users/7' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "John@gmail.com",
    "username": "johnd",
    "password": "password",
    "name": {
        "firstname": "John",
        "lastname": "Doe"
    },
    "address": {
        "city": "kilcoole",
        "street": "7835 new road",
        "number": "3",
        "geolocation": {
            "lat": "-37.3159",
            "long": "81.1496"
        }
    },
    "phone": "1-570-236-7033"
}'
```

**Comment by Dawid-Witkowski** [comment]
Resolved my issue, thanks :)
