### ISSUE TITLE
FakeStore API is down

### ISSUE THREAD

**Issue by GheorgheAlex** [keikaavousi/fake-store-api#64]
Hello! I noticed that today the API is giving a status code 502. Yesterday it was working just fine. Thank you and have a nice day!

**Comment by keikaavousi** [comment]
Hi GheorgheAlex,
Thanks for your feedback. It is working now!

**Comment by GheorgheAlex** [comment]
Thank you very much! I wish you a nice day!

**Comment by eclectic-coding** [comment]
Looks like it is down again

**Comment by BiancaMarin** [comment]
Hello! The API is giving me a status of 524. It could be something wrong with the platform? Thank you! Have a nice day!

**Comment by BiancaMarin** [comment]
Problem solved. :)
