### ISSUE TITLE
FakeStore API is down

### ISSUE THREAD

**Issue by oemurlu** [keikaavousi/fake-store-api#76]
Hi, API gives status code 522. It looks like a host error. It was working fine this morning. Thanks in advance.

**Comment by ferhatergun** [comment]
yes i was about to finish my project and all of a sudden the site was down  ,I don't know why the error occurred

**Comment by keikaavousi** [comment]
Hi!
Maybe it was a temporary glitch. It's working fine now.

**Comment by oemurlu** [comment]
I'm still getting the same error. I tried with VPN as the second way, but the result still did not change.
![image](https://user-images.githubusercontent.com/102610734/218263153-39f3ae89-2daf-4ad5-b6ee-1984bc8a6a88.png)

**Comment by keikaavousi** [comment]
It’s something related to connection between Istanbul and cloudflare due to
the latest conflicts.
Try some other VPN from Europe.

**Comment by oemurlu** [comment]
Problem fixed 👍
