### ISSUE TITLE
Fakestoreapi is down

### ISSUE THREAD

**Issue by im-ghost** [keikaavousi/fake-store-api#77]

**Comment by keikaavousi** [comment]
It's working fine, what is the exact error you get?

**Comment by iCris17** [comment]
Hello, i'm able to request a get from the google chrome browser, but getting a 522: Connection timed out error from postman and from VSCode, it's so strange and I really need it for a front-end project.

**Comment by iCris17** [comment]
> It's working fine, what is the exact error you get?

Sorry for bothering you, is there an alternative url I can get the requests from?

**Comment by keikaavousi** [comment]
No worries, I'm investigating the problem now and let you know about it.

**Comment by iCris17** [comment]
> 

I'll wait for your answer then, and thanks in advance

**Comment by iCris17** [comment]
In case you need further details:
For instance:
https://fakestoreapi.com/products. I request it on the browser and i get 20 products, when using Postman/VSCode I get that 522 error.

**Comment by iCris17** [comment]
@keikaavousi mainly i was getting the problem on the login endpoint, but somehow (in part because of my bad, i was requesting the post badly) i am not getting problems in VSCode anymore. I really thank you a lot for the assistance, blesses.

**Comment by keikaavousi** [comment]
Ohhk! No problem at all!
Good luck!

**Comment by rustydroid** [comment]
Hi @keikaavousi 
I tried today using postman to All products endpoint, and I'm getting 522 error.
`curl --location 'https://fakestoreapi.com/products.' \`

If I try with browser, like Chrome, Brave, Firefox, I'm getting a timeout from Cloudflare.
I use to use it for my test react projects, and unfortunatelly is not working.

I verified the documentation first, but
Did something changed on the API use?

Thanks in advance for your help

**Comment by keikaavousi** [comment]
Ok, I'll check it out.
*****IMPORTANT*****it will be down for the next couple of hours to fix.

**Comment by keikaavousi** [comment]
it's working now. please check it and let me know if there is any problem.

**Comment by rustydroid** [comment]
Kindly strange, it's still failing with same 522 error timeout.
ping command is returning the server ip, but the service is not responding.

**Comment by keikaavousi** [comment]
remember that if you are sending the POST request, it should be stringified
like body:JSON.stringify()

**Comment by keikaavousi** [comment]
it's under investigation. please wait for a little while

**Comment by rustydroid** [comment]
I can confirm that it's back to work.
thanks for your help!

**Comment by keikaavousi** [comment]
Glad to hear it!

**Comment by im-ghost** [comment]
> It's working fine, what is the exact error you get?

The images are not displaying

**Comment by ngdinhuy** [comment]
hi guys, api products/category/jewelery return timeout

**Comment by jecojacob** [comment]
API is down

**Comment by Anan328** [comment]
api is down again

**Comment by boby-widjaja** [comment]
It has been down again for few hours now.
