### ISSUE TITLE
522 error on the browser

### ISSUE THREAD

**Issue by iCris17** [keikaavousi/fake-store-api#78]
Sorry for bothering, but i'm definitely not able to use the API again. I have one teammate that is able to from Canada, but i don't know if the distance has to do here, since i'm in Guatemala right now:
![Captura de pantalla de 2023-03-18 16-58-51](https://user-images.githubusercontent.com/37000434/226144502-c442aea6-925b-4967-b5c4-160a5d7bf1fd.png)

**Comment by dianavul** [comment]
![image](https://user-images.githubusercontent.com/118757967/226198559-9a7d30a8-c633-4007-9ae4-666cafb0ed03.png)

same here

**Comment by knottem** [comment]
![image](https://user-images.githubusercontent.com/59744487/226349158-e2d66203-5e47-4287-8bf9-7c5bcf5baf51.png)
same here

**Comment by fryderyk1991** [comment]
![Zrzut ekranu 2023-03-20 223627](https://user-images.githubusercontent.com/95125510/226471341-4a6864a1-be84-4268-8767-15d80091e40c.png)


same here

**Comment by keikaavousi** [comment]
It seems there is an issue with some relation between Cloudflare and the
server.
I'm changing the hosting provider as soon as possible. It should work after
that.

**Comment by abhi-dasgupta** [comment]
![Screenshot 2023-03-22 001734](https://user-images.githubusercontent.com/42039510/226711165-5ce493aa-2d41-40a7-b31c-c2f162627502.png)

**Comment by jeffjiang13** [comment]
is it working yet??

**Comment by keikaavousi** [comment]
Does this problem exist?
