### ISSUE TITLE
fake store api is showing this error 

### ISSUE THREAD

**Issue by sujalshah-bit** [keikaavousi/fake-store-api#81]
Access to XMLHttpRequest at 'https://fakestoreapi.com/products/' from origin 'http://127.0.0.1:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by keikaavousi** [comment]
Does your problem still exist? it should be fixed.
it may be because of the server downtimes. it should work fine now.
let me know if you have any problems.
