### ISSUE TITLE
auth/login not working

### ISSUE THREAD

**Issue by thesanjithkumar** [keikaavousi/fake-store-api#83]
auth/login is getting timed out not able to login through post method

**Comment by keikaavousi** [comment]
Does your problem still exist? it be should fixed

**Comment by stephanepx** [comment]
Hi ! 
Same problem here

**Comment by keikaavousi** [comment]
@stephanepx @thesanjithkumar Do you still have this problem? it should be fixed now. otherwise, send your request and response here. you should provide username and password in JSON format.
