### ISSUE TITLE
get all carts not working

### ISSUE THREAD

**Issue by alon-green** [keikaavousi/fake-store-api#84]
when trying to get all the carts 
https://fakestoreapi.com/carts
getting status 400 bad request and the following response

{
    "status": "error",
    "message": "date format is not correct. it should be in yyyy-mm-dd format"
}

**Comment by keikaavousi** [comment]
Please provide startdate anddate for carts

**Comment by alon-green** [comment]
according to the docs it should work without supplying dates, to get all carts

**Comment by keikaavousi** [comment]
Yes, it will be fixed as soon as possible and I will let you know. For now,
to make it work you should provide a date.
