### ISSUE TITLE
Carts not working

### ISSUE THREAD

**Issue by MohamedSamyHossebo** [keikaavousi/fake-store-api#85]
Get all carts method not working and it Respones with type 400 error "date format is not correct. it should be in yyyy-mm-dd format"

https://fakestoreapi.com/carts

**Comment by keikaavousi** [comment]
You should provide startsate and enddate as well for now. It will be fixed
soon.

**Comment by MohamedSamyHossebo** [comment]
I provided it and still not working 😞

**Comment by keikaavousi** [comment]
You can use it like this:

https://fakestoreapi.com/carts?startdate=2019-12-10&enddate=2020-10-10


Good luck!

**Comment by keikaavousi** [comment]
@MohamedSamyHossebo It's working fine now and you can provide startdate , enddate, or none of them.
