### ISSUE TITLE
Cannot get User Carts

### ISSUE THREAD

**Issue by KaMazim** [keikaavousi/fake-store-api#87]
When trying to access the **[user cart route](https://fakestoreapi.com/carts/user/2)** , I receive the following error: 
`{"status":"error","message":"date format is not correct. it should be in yyyy-mm-dd format"} `

**Comment by keikaavousi** [comment]
Hi!
Could you please send me your exact request with all querystrings?

**Comment by KaMazim** [comment]
Hi! there were no query strings, I simply tried to access this link: https://fakestoreapi.com/carts/user/2

**Comment by anatolii-pyroh** [comment]
![image](https://user-images.githubusercontent.com/79711055/235175676-d42e998c-8b8d-4253-aa33-8a576557b91b.png)

same

**Comment by keikaavousi** [comment]
@anatolii-pyroh @KaMazim It's fixed now.
