### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by Hastalavistababy** [keikaavousi/fake-store-api#9]
`Access to fetch at 'https://fakestoreapi.com/products/1' from origin 'https://fakestoreapi.herokuapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by keikaavousi** [comment]
> `Access to fetch at 'https://fakestoreapi.com/products/1' from origin 'https://fakestoreapi.herokuapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

The problem is resolved, and you can access the API with no error

**Comment by Hastalavistababy** [comment]
> > `Access to fetch at 'https://fakestoreapi.com/products/1' from origin 'https://fakestoreapi.herokuapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
> 
> The problem is resolved, and you can access the API with no error
