### ISSUE TITLE
The API is down

### ISSUE THREAD

**Issue by gabi-alv** [keikaavousi/fake-store-api#94]
The API is currently down.
<img width="1226" alt="image" src="https://github.com/keikaavousi/fake-store-api/assets/123763857/b63f9424-ed00-4965-9c5c-ea06ffe1d685">

**Comment by KayodeAjayi200** [comment]
same experience here

**Comment by AlejandroJCR** [comment]
Same Error, anyone know when it will be fixed?

**Comment by sanciom28** [comment]
we used this API for a school project due tomorrow morning, no other API is working for us, would love it if this gets fixed really soon!!

**Comment by looksliketyler** [comment]
please update as im using for a school project as well and dont want to rewrite my entire project

**Comment by looksliketyler** [comment]
@keikaavousi ?

**Comment by gabo-android** [comment]
Just learn the lesson boy, don't put all your trust in external
dependencies or systems that you don't control, always have safewards in
place.

Also, don't spam this thread as the API maintainer is not doing it for a
pay, no need to be like this as if he owed you anything.

Finally , do your homework and host this code in your own server or in a
public free service like herokuapp, as the author was kind enough to share
the code with us in GH for free.

**Comment by keikaavousi** [comment]
It's working now. You can enjoy it ;)

**Comment by gabi-alv** [comment]
@keikaavousi you saved someone's homework today. Great work and thank you sir for providing this api 🫡

**Comment by QuentinJanuel** [comment]
It's down again
